#!/bin/bash

which ansible-playbook > /dev/null 2>&1
if [ $? -ne 0 ]; then
	apt-get update
	DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

	DEBIAN_FRONTEND=noninteractive apt-get install python3 python3-pip -y

	pip3 install ansible==5.4.0
fi

ansible-playbook ./kube-host.yaml
